### ISSUE TITLE
Unable to create VM with nested_enabled

### ISSUE THREAD

**Issue by AjiArya** [AjiArya/python-tfgen#1]
# Evidence
![image](https://user-images.githubusercontent.com/53201929/168009141-033f05ad-6800-47a1-99a1-0194cc783b95.png)

# YAML
```yaml
kind: vm
spec:
  - name: vm1
    hostname: vm1
    nested_enabled: true
    os: ubuntu
    vcpus: 2
    memory: 2G
    console: vnc
    cloud_data:
      users:
        - name: user1
          password: strongpassword
          sudo: true
    base_image:
      storage_pool: isos
      name: template-ubuntu20.img
    disks:
      storage_pool: vms
      disk_format: qcow2
      disks:
        - name: vm1-vda.qcow2
          size: 10G
        - name: vm1-vdb.qcow2
          size: 10G
    networks:
      - name: net-192.168.1
        address: 192.168.1.11/24
        gateway: 192.168.1.1
        dns: [8.8.8.8, 8.8.4.4]
```
